// src/utils/statusDescriptions.ts

export const statusDescriptions: Record<string, string> = {
  // 1xx - Informational
  "100": "Continue: The server has received the request headers; the client should proceed to send the request body.",
  "101": "Switching Protocols: The requester has asked the server to switch protocols; the server is confirming that switch.",
  "102": "Processing: The server has received and is processing the request, but no response is available yet.",
  "103": "Early Hints: The server is likely to send a final response with the header fields included in the informational response.",

  // 2xx - Success
  "200": "OK: The request succeeded. The result depends on the HTTP method used.",
  "201": "Created: The request succeeded, and a new resource was created as a result.",
  "202": "Accepted: The request has been received but not yet acted upon.",
  "203": "Non-Authoritative Information: The request was successful but the enclosed payload has been modified.",
  "204": "No Content: The server successfully processed the request and is not returning any content.",
  "205": "Reset Content: The server successfully processed the request and asks that the requester reset its document view.",
  "206": "Partial Content: The server is delivering only part of the resource due to a range header sent by the client.",
  "207": "Multi-Status: The message body contains multiple separate responses.",
  "208": "Already Reported: Members of a DAV binding have already been enumerated in a previous reply.",
  "226": "IM Used: The server has fulfilled a request for the resource using the instance manipulations supplied by the request.",

  // 3xx - Redirection
  "300": "Multiple Choices: The request has more than one possible response.",
  "301": "Moved Permanently: The URL of the requested resource has been changed permanently.",
  "302": "Found: The URI of requested resource has been changed temporarily.",
  "303": "See Other: The server is redirecting to a different URI using the GET method.",
  "304": "Not Modified: The resource has not been modified since the last request.",
  "305": "Use Proxy: The requested resource is available only through a proxy. Deprecated.",
  "307": "Temporary Redirect: The server is redirecting to a different URI but the request method should not be changed.",
  "308": "Permanent Redirect: The resource is now permanently located at a different URI.",

  // 4xx - Client errors
  "400": "Bad Request: The server could not understand the request due to invalid syntax.",
  "401": "Unauthorized: The client must authenticate itself to get the requested response.",
  "402": "Payment Required: Reserved for future use.",
  "403": "Forbidden: The client does not have access rights to the content.",
  "404": "Not Found: The server can not find the requested resource.",
  "405": "Method Not Allowed: The request method is known but has been disabled.",
  "406": "Not Acceptable: The requested resource is capable of generating only content not acceptable to the client.",
  "407": "Proxy Authentication Required: The client must authenticate with a proxy.",
  "408": "Request Timeout: The server would like to shut down this unused connection.",
  "409": "Conflict: The request conflicts with the current state of the server.",
  "410": "Gone: The requested resource is no longer available and will not be available again.",
  "411": "Length Required: The request did not specify the length of its content.",
  "412": "Precondition Failed: The server does not meet one of the preconditions specified by the client.",
  "413": "Payload Too Large: The request is larger than the server is willing or able to process.",
  "414": "URI Too Long: The URI requested by the client is longer than the server is willing to interpret.",
  "415": "Unsupported Media Type: The media format of the requested data is not supported by the server.",
  "416": "Range Not Satisfiable: The range specified by the Range header field in the request can't be fulfilled.",
  "417": "Expectation Failed: The expectation given in the request's Expect header could not be met.",
  "418": "I'm a teapot: This code was defined in 1998 as an April Fools' joke.",
  "421": "Misdirected Request: The request was directed at a server that is not able to produce a response.",
  "422": "Unprocessable Content: The server understands the content type but was unable to process the contained instructions.",
  "423": "Locked: The resource that is being accessed is locked.",
  "424": "Failed Dependency: The request failed due to failure of a previous request.",
  "425": "Too Early: The server is unwilling to risk processing a request that might be replayed.",
  "426": "Upgrade Required: The server refuses to perform the request using the current protocol.",
  "428": "Precondition Required: The origin server requires the request to be conditional.",
  "429": "Too Many Requests: The user has sent too many requests in a given amount of time.",
  "431": "Request Header Fields Too Large: The server is unwilling to process the request because its header fields are too large.",
  "451": "Unavailable For Legal Reasons: The user-agent requested a resource that cannot legally be provided.",

  // 5xx - Server errors
  "500": "Internal Server Error: The server has encountered a situation it doesn't know how to handle.",
  "501": "Not Implemented: The request method is not supported by the server and cannot be handled.",
  "502": "Bad Gateway: The server received an invalid response from the upstream server.",
  "503": "Service Unavailable: The server is not ready to handle the request.",
  "504": "Gateway Timeout: The server is acting as a gateway and cannot get a response in time.",
  "505": "HTTP Version Not Supported: The HTTP version used in the request is not supported by the server.",
  "506": "Variant Also Negotiates: The server has an internal configuration error.",
  "507": "Insufficient Storage: The server is unable to store the representation needed to complete the request.",
  "508": "Loop Detected: The server detected an infinite loop while processing the request.",
  "510": "Not Extended: Further extensions to the request are required for the server to fulfill it.",
  "511": "Network Authentication Required: The client needs to authenticate to gain network access.",
};
